FROM your-org-clients:latest AS builder

COPY ./deploy/prod/.env.prod-local /app/.env.prod-local
RUN export $(grep -v '^#' /app/.env.prod-local | xargs) && npm run build

FROM caddy:2.9.1

COPY --from=builder /app/clients/spas/dist /srv/spas
COPY ./deploy/prod/remote-assets/config /etc/caddy/
COPY ./deploy/prod/remote-assets/health-assets /srv/health-assets
