name: Demo checklist

on:
  pull_request:
    branches:
      - main

jobs:
  demo-checklist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install submodules
        run: git submodule update --init
      - name: Install dependencies
        run: npm ci

      # Run every workflow checklist. This should error if any error
      - name: Run Workflow Integration Test
        run: npm exec saf-workflow checklist ./workflows/demo.ts
