name: Workflows in Script Mode

on:
  pull_request:
    branches:
      - main

jobs:
  workflow-integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      # Main test. If this fails, one of the workflows is broken.
      - name: Run Workflow Integration Test
        run: npm exec saf-workflow run-scripts ./workflows/demo.ts

      # just for debugging, checking all the files that got added/changed
      - name: Git status
        run: git status -uall
